//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public string Namad { get; set; }
        public string TradingDate { get; set; }
        public Nullable<int> CountOfPortion { get; set; }
        public Nullable<int> AvverageCost { get; set; }
        public Nullable<int> RealCost { get; set; }
        public Nullable<bool> FirstOffer { get; set; }
        public string OwnerName { get; set; }
        public long id { get; set; }
        public Nullable<int> InvestmentType { get; set; }
        public string Description { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string BrokerName { get; set; }
    }
}
