//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketShopping
    {
        public long Id { get; set; }
        public long BasketID { get; set; }
        public string ShoppingDate { get; set; }
        public int ShopCount { get; set; }
        public long ShoppingCost { get; set; }
        public string Description { get; set; }
    }
}
