//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Namad
    {
        public long ID { get; set; }
        public string Namad1 { get; set; }
        public string Name { get; set; }
        public string GeneralCode { get; set; }
        public Nullable<long> tseID { get; set; }
        public string EnNamad { get; set; }
        public string EnName { get; set; }
        public string NamadGroup { get; set; }
        public string TableName { get; set; }
        public Nullable<long> IndustryID { get; set; }
    }
}
