//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradingData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Trading]
        ///GO
        ////****** Object:  UserDefinedFunction [dbo].[GregorianToPersian]    Script Date: 9/7/2020 8:15:26 AM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	&lt;Description,,&gt;
        ///-- =============================================
        ///Create FUNCTION [dbo].[GregorianToPersian]
        ///(
        ///@Date varchar(10)
        ///)
        ///RETURNS varchar(10)
        ///AS
        ///BEGIN    DECLARE @ResultVar varchar(10)
        ///de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0001_Create_Database {
            get {
                return ResourceManager.GetString("0001_Create_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Trading]
        ///GO
        ////****** Object:  StoredProcedure [dbo].[procCalculateMemberBenefits]    Script Date: 9/15/2020 11:49:59 PM ******/
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	&lt;Description,,&gt;
        ///-- =============================================
        ///ALTER PROCEDURE [dbo].[procCalculateMemberBenefits]
        ///	@GroupId as int
        ///	-- Add the parameters for the stored procedure here
        ///AS        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0002_AlterCalculateGroupBenefitProc {
            get {
                return ResourceManager.GetString("0002_AlterCalculateGroupBenefitProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   update [Trading].[dbo].[Payments] set TransactionType = N&apos;واریز وجه&apos; where TransactionType = N&apos;پرداخت&apos;
        ///  update [Trading].[dbo].[Payments] set TransactionType = N&apos;برداشت وجه&apos; where TransactionType = N&apos;برداشت&apos;
        ///.
        /// </summary>
        internal static string _0003_Update_Data {
            get {
                return ResourceManager.GetString("0003_Update Data", resourceCulture);
            }
        }
    }
}
